"use strict";const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),core=require("../labs/parallel-distributed-graphs-core.js");
const atlasRoot=path.join(__dirname,"..");
const chapterSource=fs.readFileSync(path.join(atlasRoot,"chapters/parallel-distributed-graphs.html"),"utf8");
const adapterSource=fs.readFileSync(path.join(atlasRoot,"labs/parallel-distributed-graphs.js"),"utf8");
function finish(s){while(!s.finished)s=core.step(s);return s;}
test("BFS-волны совпадают с последовательным эталоном",()=>{for(const name of Object.keys(core.PRESETS)){const g=core.graphFromPreset(name),p=core.PRESETS[name],s=finish(core.createState({graph:g,source:p.source||undefined,workers:4,bandwidth:8}));assert.equal(JSON.stringify(s.current.distance),JSON.stringify(s.reference.distance),name);assert.equal(s.current.parallelWork,s.reference.work,name);}});
test("путь имеет линейное число уровней, звезда — два",()=>{const p=finish(core.createState({graph:core.graphFromPreset("path"),source:"0"}));const s=finish(core.createState({graph:core.graphFromPreset("star"),source:"c"}));assert.equal(p.current.rounds,9);assert.equal(s.current.rounds,2);});
test("несвязные вершины не получают расстояние",()=>{const s=finish(core.createState({graph:core.graphFromPreset("disconnected"),source:"s"}));assert.equal(s.current.distance.x,undefined);assert.deepEqual(s.current.visited.slice().sort(),["a","b","s"]);});
test("параллельные рёбра и петля входят в work/messages, но не портят уровни",()=>{const s=finish(core.createState({graph:core.graphFromPreset("parallel"),source:"s"}));assert.deepEqual(s.current.distance,{s:0,a:1,b:2});assert.ok(s.current.totalMessages>=6);});
test("маленькая bandwidth увеличивает число подраундов, а пустой канал их не создаёт",()=>{const g=core.graphFromPreset("wave");const low=core.createState({graph:g,source:"s",bandwidth:1}),high=core.createState({graph:g,source:"s",bandwidth:64});assert.ok(low.frames[0].subrounds>high.frames[0].subrounds);const singleton=core.createState({graph:core.graphFromPreset("singleton"),source:"v"});assert.equal(singleton.frames[0].roundMessages,0);assert.equal(singleton.frames[0].subrounds,0);});
test("нагрузка по секциям, текущая коммуникация и skew конечны",()=>{const s=core.createState({graph:core.graphFromPreset("skew"),source:"a",workers:4});s.frames.forEach(f=>{assert.equal(f.partitionLoads.length,4);assert.ok(Number.isFinite(f.skew));assert.ok(f.roundCrossPartitionMessages<=f.roundMessages);assert.ok(f.crossPartitionMessages<=f.totalMessages);});});
function randomGraph(seed){let x=seed>>>0;const rnd=()=>((x=(1664525*x+1013904223)>>>0)/2**32);const n=1+Math.floor(rnd()*12),nodes=Array.from({length:n},(_,i)=>({id:"v"+i,label:"v"+i})),edges=[];for(let i=0;i<n;i++)for(let j=i;j<n;j++)if(rnd()<.22)edges.push({id:"e"+(edges.length+1),source:"v"+i,target:"v"+j});return{nodes,edges};}
test("120 случайных графов совпадают с независимым BFS",()=>{for(let seed=1;seed<=120;seed++){const g=randomGraph(seed),ref=core.bfsReference(g,"v0"),s=finish(core.createState({graph:g,source:"v0",workers:1+seed%8,bandwidth:1+seed%32}));assert.equal(JSON.stringify(s.current.distance),JSON.stringify(ref.distance),"seed="+seed);assert.equal(s.current.sequentialWork,ref.work);}});
test("парсер ограничен и сохраняет параллельные рёбра",()=>{assert.equal(core.parseGraphText("a,b","a b\na b").edges.length,2);assert.throws(()=>core.parseGraphText("a","a z"),/неизвестную/);const many=Array.from({length:core.MAX_NODES+1},(_,i)=>"v"+i).join(",");assert.throws(()=>core.parseGraphText(many,""),/не более/);});
test("неизвестный источник отклоняется до построения кадров",()=>{assert.throws(()=>core.createState({graph:core.graphFromPreset("wave"),source:"missing"}),/Неизвестный источник/);});
test("playback неизменяем и поддерживает общий контракт",()=>{const s=core.createState({graph:core.graphFromPreset("wave"),source:"s"});assert.ok(Object.isFrozen(s));assert.equal(core.step(s).cursor,1);assert.equal(core.reset(core.step(s)).cursor,0);assert.ok(core.seek(s,s.frames.length-1).finished);});
test("страница и adapter используют общий full-width graph runtime без исполняемого парсера",()=>{assert.match(chapterSource,/data-atlas-node-id="parallel-distributed-graphs"/);assert.match(chapterSource,/class="atlas-block atlas-block--fullwidth" data-atlas-block="lab"/);assert.match(chapterSource,/data-atlas-lab="parallel-distributed-graphs"/);assert.match(chapterSource,/graph-lab-core\.js/);assert.match(chapterSource,/graph-lab-runtime\.js/);assert.match(chapterSource,/graph-labs\.css/);assert.match(adapterSource,/AtlasGraphLabRuntime/);assert.match(adapterSource,/graphRuntime\.mount/);assert.match(adapterSource,/runtime\.mount/);assert.match(adapterSource,/maxAutomaticSteps:core\.MAX_NODES\+2/);assert.doesNotMatch(chapterSource+adapterSource,/\beval\s*\(|\bnew\s+Function\b|\bFunction\s*\(/);assert.equal((chapterSource.match(/class="atlas-exercise"/g)||[]).length,12);});
test("каждая интерактивная формула имеет точный ненулевой набор обозначений",()=>{const formulas=chapterSource.match(/<div class="atlas-math atlas-notation-formula"[\s\S]*?<\/div>/g)||[];assert.equal(formulas.length,8);const ids=[];for(const formula of formulas){const id=formula.match(/data-formula-id="([a-z0-9-]+)"/);const requiredMatch=formula.match(/data-required-notations="([a-z0-9,-]+)"/);assert.ok(id);assert.ok(requiredMatch);ids.push(id[1]);assert.match(formula,/data-notation-coverage="interactive"/);const required=requiredMatch[1].split(",");const tokens=Array.from(formula.matchAll(/notation-id-([a-z0-9-]+)/g),match=>match[1]);assert.equal(required.length,new Set(required).size,id[1]);assert.equal(tokens.length,new Set(tokens).size,id[1]);assert.deepEqual(new Set(tokens),new Set(required),id[1]);}assert.equal(ids.length,new Set(ids).size);});
